server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: cedupscore-api

  data-source:
    platform: mysql
    url: jdbc:mysql://localhost:3306/db_cedupscore
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
