server:
  port: 8080

spring:
  data-source:
    url: jdbc:h2:mem:dev_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    data: classpath:/data.sql

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
