server:
  port: 8081

spring:
  data-source:
    platform: mysql
    url: jdbc:mysql://localhost:3306/db_cedupscore
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
